config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations, invitations: :invitations }

  resources :settings, only: [:new, :create]

  resources :bots do
    resources :events, only: [:create]
    resources :dashboards, only: [:index, :show, :new, :create, :destroy] do
      member do
        get :load_async
      end
    end

    resources :short_links, only: [:create]
    resources :paths do
      member do
        get :insights
        get :events
      end
    end

    get :verifying_webhook
    get :webhook_events, on: :member

    resources :instances, only: [:new, :create, :show, :edit, :update], controller: :bot_instances do
      member do
        get :setting_up
      end
    end

    resources :users, controller: "bot_users", only: [:update], as: :users

    resources :retention, only: [:index]

    resources :notifications, except: [:new, :create, :edit, :update]
    resources :new_notification, only: [:create] do
      collection do
        get :step_1
        get :step_2
        get :step_3
      end
    end
    resources :edit_notification, only: [:update] do
      member do
        get :step_1
        get :step_2
        get :step_3
      end
    end

    resources :messages, only: [:create]

    resources :insights, only: [:index]
  end

  resources :users, only: [:show, :update] do
    member do
      patch :regenerate_api_key
    end
  end

  resources :short_links, only: [:show], path: 'to'

  root 'static#index'

  get '/.well-known/acme-challenge/:id' => 'static#letsencrypt', protocol: 'http'
  get '/privacy' => 'static#privacy'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web, at: "/sidekiq"

  unless Rails.env.production?
    mount SlackApiMocks, at: "/slack_api_mocks"
    mount FacebookApiMocks, at: "/facebook_api_mocks"
  end
end

app/controllers/retention_controller.rb
class RetentionController < ApplicationController
  before_action :authenticate_user!
  before_action :find_bot

  layout 'app'

  def index
    @group_by = params[:group_by].presence || 'week'
    @start = params[:start].to_s.in_time_zone(current_user.timezone) || 4.weeks.ago
    @end = params[:end].to_s.in_time_zone(current_user.timezone) || Time.current

    @retention = retention_metrics
  end

  private
  def retention_metrics
    periods = 0
    retention = []

    case @group_by
    when 'day'
      periods = ((@end.to_i - @start.to_i).to_f / (24 * 60 * 60)).ceil
      (0...periods).each do |period|
        retention << BotUser.by_cohort(@bot, start_time: @start + period.days, end_time: @end, group_by: @group_by)
      end
    when 'week'
      periods = ((@end.to_i - @start.to_i).to_f / (24 * 60 * 60 * 7)).ceil
      (0...periods).each do |period|
        retention << BotUser.by_cohort(@bot, start_time: @start + period.weeks, end_time: @end, group_by: @group_by)
      end
    when 'month'
      periods = ((@end.to_i - @start.to_i).to_f / (24 * 60 * 60 * 30)).ceil
      (0...periods).each do |period|
        retention << BotUser.by_cohort(@bot, start_time: @start + period.months, end_time: @end, group_by: @group_by)
      end
    end

    retention
  end
end

app/views/retention/index.html.haml
.secondary-menu.row
  .col-md-5.col-sm-3.col-xs-6
    = link_to bot_dashboards_path(@bot), class: 'breadcrumb' do
      %h2 All Metrics
    %span.breadcrumb-separator
      \/
    %h2
      Retention
  .col-md-7.col-sm-9.col-xs-6.text-right
    #report-range.pull-right
      = icon('calendar')
      %span
      %b.caret
    .btn-group.time-segmented-controls.pull-right
      = link_to 'Daily', bot_retention_index_path(@bot), class: (@group_by == 'day' ? 'btn active' : 'btn'), data: { group: 'day' }
      = link_to 'Weekly', bot_retention_index_path(@bot, group_by: 'week'), class: (@group_by == 'week' ? 'btn active' : 'btn'), data: { group: 'week' }
      = link_to 'Monthly', bot_retention_index_path(@bot, group_by: 'month'), class: (@group_by == 'month' ? 'btn active' : 'btn'), data: { group: 'month' }

.container-fluid.retention-container
  .graph.row
    .col-md-12.col-sm-12.col-xs-12#retention

- content_for :page_scripts do
  :javascript
    App.page = new App.RetentionIndex(#{@retention.to_json}, #{@start.to_json}, #{@end.to_json}, #{@group_by.to_json});
    App.page.run();