config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations, invitations: :invitations }

  resources :settings, only: [:new, :create]

  resources :bots do
    resources :events, only: [:create]
    resources :dashboards, only: [:index, :show, :new, :create, :destroy] do
      member do
        get :load_async
      end
    end

    resources :short_links, only: [:create]
    resources :paths do
      member do
        get :insights
        get :events
      end
    end

    get :verifying_webhook
    get :webhook_events, on: :member

    resources :instances, only: [:new, :create, :show, :edit, :update], controller: :bot_instances do
      member do
        get :setting_up
      end
    end

    resources :users, controller: "bot_users", only: [:update], as: :users

    resources :retention, only: [:index]

    resources :notifications, except: [:new, :create, :edit, :update]
    resources :new_notification, only: [:create] do
      collection do
        get :step_1
        get :step_2
        get :step_3
      end
    end
    resources :edit_notification, only: [:update] do
      member do
        get :step_1
        get :step_2
        get :step_3
      end
    end

    resources :messages, only: [:create]

    resources :insights, only: [:index]
  end

  resources :users, only: [:show, :update] do
    member do
      patch :regenerate_api_key
    end
  end

  resources :short_links, only: [:show], path: 'to'

  root 'static#index'

  get '/.well-known/acme-challenge/:id' => 'static#letsencrypt', protocol: 'http'
  get '/privacy' => 'static#privacy'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web, at: "/sidekiq"

  unless Rails.env.production?
    mount SlackApiMocks, at: "/slack_api_mocks"
    mount FacebookApiMocks, at: "/facebook_api_mocks"
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  include WithUidUniqueness

  belongs_to :bot

  has_one :query_set, dependent: :destroy
  has_many :messages, dependent: :destroy

  validates_presence_of :content

  with_options on: :schedule do |n|
    n.validate :verify_scheduled_at
  end

  def send_immediately?
    scheduled_at.blank?
  end

  def sent?
    return true if scheduled_at.blank?

    schedule_at_in_past?
  end

  private
  def verify_scheduled_at
    return if scheduled_at.blank?

    if self.recurring?
      if !scheduled_at.match /\A(?:[1-9]|1[0-2]):[0-5][0-9][ap]m\Z/im
        errors.add(:scheduled_at, 'is invalid for a recurring notification')
      end
    else
      if schedule_at_in_past?
        errors.add(:scheduled_at, 'has already past in some time zones')
      end
    end
  end

  def schedule_at_in_past?
    !self.recurring? && scheduled_at.in_time_zone('Pacific/Apia').past?
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_bot
  before_action :find_notification,   only: [:show, :destroy]
  before_action :valid_notification?, only: [:destroy]

  layout 'app'

  def index
    @notifications = @bot.notifications.order(id: :desc).page(params[:page])
    redirect_to(step_1_bot_new_notification_index_path(@bot)) && return if @notifications.blank?
  end

  def show
    @send_count = FilterBotUsersService.new(@notification.query_set).scope.size

    respond_to do |format|
      format.html { render :show }
      format.json { render json: { sent: @notification.messages.sent.count } }
    end
  end

  def destroy
    @notification.destroy

    redirect_to bot_notifications_path(@bot), notice: 'The notification has been deleted.'
  end

  private
  def find_notification
    @notification = @bot.notifications.find_by!(uid: params[:id])
  end

  def valid_notification?
    raise ActiveRecord::RecordNotFound if @notification.sent?
  end

  def model_params
    params.require(:notification).permit(:content, :scheduled_at)
  end
end

app/views/notifications/index.html.haml
.secondary-menu.row
  .col-md-4.col-sm-4.col-xs-4
    %h2 All Notifications
  .col-md-8.col-sm-8.col-xs-8.text-right
    .btn-group
      = link_to step_1_bot_new_notification_index_path(@bot), class: 'btn btn-primary' do
        New Notification

.container-fluid.notifications-container
  .row
    .col-sm-8.col-sm-offset-2
      %table.table.table-striped.tableized
        %thead
          %tr
            %th Content
            %th Status
            %th Scheduled/Sent At
            %th Actions
        %tbody
          - @notifications.each do |notification|
            %tr
              %td= truncate(notification.content, length: 20)
              %td
                - if notification.send_immediately?
                  #{notification.messages.count} Queued / #{notification.messages.sent.count} Sent / #{notification.messages.failure.count} Failed / #{notification.messages.success.count} Success
                - else
                  - total_count = FilterBotUsersService.new(notification.query_set).scope.size if (total_count = notification.messages.count) == 0
                  #{total_count} Queued / #{notification.messages.sent.count} Sent / #{notification.messages.failure.count} Failed / #{notification.messages.success.count} Success
              %td
                - if notification.send_immediately?
                  = notification.created_at.strftime('%b %d, %Y %l:%M %p')
                - else
                  = notification.recurring? ? "#{notification.scheduled_at} every day" : notification.scheduled_at
              %td
                - if notification.sent?
                  .text-muted
                    %em Already Sent
                - else
                  = link_to step_1_bot_edit_notification_path(@bot, notification) do
                    = icon('wrench')
                    Edit
                  &nbsp;|&nbsp;
                  = link_to bot_notification_path(@bot, notification), method: :delete do
                    = icon('trash')
                    Delete

      = will_paginate @notifications, renderer: BootstrapPagination::Rails

app/views/notifications/new.html.haml
.secondary-menu.row
  .col-md-6.col-sm-3.col-xs-6
    = link_to bot_notifications_path(@bot), class: 'breadcrumb' do
      %h2 All Notifications
    %span.breadcrumb-separator
      \/
    %h2 New Notification

.container-fluid.notifications-container
  .row
    .col-sm-8.col-sm-offset-2
      - if @bot.notifications.count == 0
        .no-notifications
          %p
            With notifications you can send product announcements / maintenance window announcments and so on
            to your users. Notifications will only be sent to users
            %strong
              who have interacted with your bot at least once.
          %p
            - _time = 2.days.from_now
            You can also schedule your notification to be sent at a specific time. For e.g. if you schedule your message to be sent at
            = _time.strftime("%B %d, %Y 9:00AM")
            , the notification will be sent
            %strong
              at 9AM in each user's timezone
            on
            = _time.strftime("%B %e")
      = render 'form', bot: @bot, notification: @notification

app/views/notifications/show.html.haml
.secondary-menu.row
  .col-md-6.col-sm-3.col-xs-6
    = link_to bot_notifications_path(@bot), class: 'breadcrumb' do
      %h2 All Notifications
    %span.breadcrumb-separator
      \/
    %h2 Notification

.container-fluid.notifications-container
  .row
    .col-sm-8.col-sm-offset-2
      %p
        %strong Notification to #{pluralize(@send_count, 'User')}

      .progress.progress-striped.active
        .progress-bar.progress-bar-success{role: "progressbar", 'aria-valuenow' => "0", 'aria-valuemin' => "0", 'aria-valuemax' => "100", data: { sent: @notification.messages.sent.count, total: @send_count } }
          %span.progress-sent  #{@notification.messages.sent.count}
          \/
          %span.progress-total #{@send_count}

      .failures
        %ul
          - @notification.messages.failure.each do |message|
            %li Failed to send message to #{message.user}

- content_for :page_scripts do
  :javascript
    App.page = new App.NotificationSendingProgress(#{@bot.uid.to_json}, #{@notification.uid.to_json}, #{Pusher.key.to_json});
    App.page.run();