config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations, invitations: :invitations }

  resources :settings, only: [:new, :create]

  resources :bots do
    resources :events, only: [:create]
    resources :dashboards, only: [:index, :show, :new, :create, :destroy] do
      member do
        get :load_async
      end
    end

    resources :short_links, only: [:create]
    resources :paths do
      member do
        get :insights
        get :events
      end
    end

    get :verifying_webhook
    get :webhook_events, on: :member

    resources :instances, only: [:new, :create, :show, :edit, :update], controller: :bot_instances do
      member do
        get :setting_up
      end
    end

    resources :users, controller: "bot_users", only: [:update], as: :users

    resources :retention, only: [:index]

    resources :notifications, except: [:new, :create, :edit, :update]
    resources :new_notification, only: [:create] do
      collection do
        get :step_1
        get :step_2
        get :step_3
      end
    end
    resources :edit_notification, only: [:update] do
      member do
        get :step_1
        get :step_2
        get :step_3
      end
    end

    resources :messages, only: [:create]

    resources :insights, only: [:index]
  end

  resources :users, only: [:show, :update] do
    member do
      patch :regenerate_api_key
    end
  end

  resources :short_links, only: [:show], path: 'to'

  root 'static#index'

  get '/.well-known/acme-challenge/:id' => 'static#letsencrypt', protocol: 'http'
  get '/privacy' => 'static#privacy'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web, at: "/sidekiq"

  unless Rails.env.production?
    mount SlackApiMocks, at: "/slack_api_mocks"
    mount FacebookApiMocks, at: "/facebook_api_mocks"
  end
end

app/models/bot.rb
class Bot < ActiveRecord::Base
  include WithUidUniqueness

  validates_presence_of  :name, :provider

  PROVIDERS = {
    'facebook' => true,
    'slack' => true,
    'kik' => true,
    'telegram' => false,
    'amazon' => false
  }

  validates_inclusion_of :provider, in: PROVIDERS.keys
  validates_format_of    :webhook_url, with: %r(\Ahttps://), if: ->(record) { record.webhook_url.present? }

  has_many :instances, class_name: 'BotInstance'

  has_many :bot_collaborators
  has_many :collaborators, through: :bot_collaborators, source: :user
  has_many :owners, -> { where("bot_collaborators.collaborator_type" => 'owner') }, through: :bot_collaborators, source: :user
  has_many :funnels

  has_many :notifications
  has_many :webhook_events
  has_many :dashboards

  scope :enabled,     -> { where(enabled: true) }

  def build_instance(params)
    instance = instances.find_by(provider: provider)
    if instance.present? && instance.provider != 'slack'
      return instance.assign_attributes(params) || instance
    end
    instances.build(params)
  end

  def events
    Event.where(bot_instance_id: self.instances.select(:id))
  end

  def create_default_dashboards_with!(owner)
    Dashboard.const_get(:"DEFAULT_#{self.provider.upcase}_DASHBOARDS").each do |type|
      if self.dashboards.find_by(dashboard_type: type).blank?
        dashboard = self.dashboards.new(
          name: Dashboard.name_for(type),
          dashboard_type: type,
          bot: self,
          user: owner,
          provider: self.provider,
          default: true
        )
        dashboard.set_event_type_and_query_options!
        dashboard.save!
      end
    end
  end

  def update_first_received_event_at!
    Bot.with_advisory_lock("update-first-received-event-#{self.id}") do
      if self.first_received_event_at.blank?
        self.update_attribute(:first_received_event_at, Time.now)
      end
    end
  end
end

app/controllers/bots_controller.rb
class BotsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_bot, except: [:new, :create, :index]

  layout 'app'

  def new
    @bot = current_user.bots.build

    render :new, layout: 'devise'
  end

  def index
    if(bot = current_user.bots.enabled.first).present?
      redirect_to bot_path(bot)
    else
      flash[:info] = "You need to create a bot first!"
      redirect_to new_bot_path
    end
  end

  def create
    @bot = Bot.new(bot_params)

    if @bot.save
      bc = current_user.bot_collaborators.create(bot: @bot, collaborator_type: 'owner', confirmed_at: Time.now)
      if bc.persisted?
        @bot.create_default_dashboards_with!(current_user)
        redirect_to bot_path(@bot)
      else
        @bot.destroy
        @bot.errors.base.add 'unexpected error while creating your bot'
        render :new
      end
    else
      render :new
    end
  end

  def edit
  end

  def update
    old_webhook_url = @bot.webhook_url

    if @bot.update(bot_params)
      if @bot.webhook_url.present? && @bot.webhook_url != old_webhook_url
        redirect_to bot_verifying_webhook_path(@bot)
      else
        redirect_to bot_path(@bot)
      end
    else
      render :edit
    end
  end

  def show
    session[:bot_id] = @bot.uid
    if Setting.hostname.blank?
      redirect_to(new_setting_path) && return
    end

    @group_by = params[:group_by].presence || 'today'

    if (@instances = @bot.instances.legit).count == 0
      redirect_to(new_bot_instance_path(@bot)) && return
    end

    redirect_to bot_dashboards_path(@bot)
  end

  def destroy
    @bot.update_attribute(:enabled, false)
    session[:bot_id] = nil

    flash[:info] = "'#{@bot.name}' has been deleted and metrics collection has been disabled"
    redirect_to bots_path
  end

  def verifying_webhook
    ValidateWebhookAndUpdatesJob.perform_in(0.5.seconds, @bot.id)
  end

  def webhook_events
    @tableized = @bot.webhook_events.order("id DESC").page(params[:page])
  end

  protected

  def bot_params
    params.require(:bot).permit(:name, :webhook_url, :provider)
  end
end

app/helpers/bots_helper.rb
module BotsHelper
  def solo_chartjs_opts(group_by)
    {
      library: {
        elements: {
          point: {
            radius: 6
          },
          line: {
            borderWidth: 5,
            lineTension: 0.0
          },
        },
        scales: {
          yAxes: [
            {
              ticks: {
                fontSize: 16
              }
            }
          ],
          xAxes: [
            {
              ticks: {
                fontSize: group_by == 'hour' ? 10 : 16
              },
              time: {
                displayFormats: {
                  'day': 'MMM D',
                  'week': 'MMM D',
                  'hour': 'MMM D, HH:mm'
                }
              }
            }
          ]
        }
      }
    }
  end

  def dashboard_chartjs_opts
    {
      height: '60px',
      library: {
        elements: {
          point: {
            radius: 0
          },
          line: {
            borderWidth: 6,
            lineTension: 0.0
          },
        },
        scales: {
          xAxes: [{display: false}],
          yAxes: [
            {
              color: '#fff',
              ticks: {
                fontSize: 8,
                fontColor: '#fff'
              },
              gridLines: {
                drawOnChartArea: false,
                color: '#fff',
                drawTicks: false
              },
              scaleLabel: {
                fontSize: 0,
                fontColor:'#fff'
              }
            }
          ]
        }
      }
    }
  end

  def formatted_growth(growth)
    if growth.present?
      growth = growth * 100
      klass = growth > 0 ? 'positive' : 'negative'

      icon = if growth.to_f == 0.0
               "<i class='fa fa-arrows-h'></i>"
             elsif growth.to_f > 0.0
               "<i class='fa fa-arrow-up'></i>"
             else
               "<i class='fa fa-arrow-down'></i>"
             end

      "<p class='growth #{klass}'>#{icon}#{number_to_percentage(growth, precision: 0)}</p>".html_safe
    else
      nil
    end
  end

  def formatted_elapsed_time(time)
    time > 1 ? "#{"%.2f" % time} secs" : "#{"%.2f" % (time * 1000)} ms"
  end

  def webhook_label(bot)
    return 'Webhook URL' if bot.webhook_url.blank?

    if bot.webhook_status
      'Webhook URL <i class="fa fa-check webhook-success"></i>'.html_safe
    else
      'Webhook URL <i class="fa fa-exclamation-triangle webhook-failed"></i>'.html_safe
    end
  end
end

app/views/bots/_api.html.haml
%h3.api cURL
%p.api
  You can add more instances to your bot via an HTTP API:
%pre.api.pre-scrollable
  :preserve
    curl -X POST \
    -H "Authorization: #{current_user.api_key}" \
    #{Settings.rails_host}/bots/#{@bot.uid}/instances \
    -d "format=json&instance[token]=my-bot-token"
%h3.api Ruby
%p.api
  You can also use the Rubygem
  %code botmetrics-rb
  available at
  = link_to 'botmetrics/botmetrics-rb', 'https://github.com/botmetrics/botmetrics-rb'
  Set the following environment variables in your app:
  %pre.api.pre-scrollable
    :preserve
      BOTMETRICS_BOT_ID=#{@bot.uid}
      BOTMETRICS_API_KEY=#{current_user.api_key}
%h3.api Node.JS
%p.api
  You can also use the NPM module
  %code botmetrics.js
  available at
  = link_to 'botmetrics/botmetrics.js', 'https://github.com/botmetrics/botmetrics.js'
  Set the following environment variables in your app:
  %pre.api.pre-scrollable
    :preserve
      BOTMETRICS_BOT_ID=#{@bot.uid}
      BOTMETRICS_API_KEY=#{current_user.api_key}
%p.api
  and follow along the
  = link_to 'README', 'https://github.com/botmetrics/botmetrics-rb'
  for the rest of the instructions.

app/views/bots/_api_others.html.haml
.api
  %ul.nav.nav-pills.nav-code{role: 'tablist'}
    %li.active{role: 'presentation'}
      %a{href: '#nodejs', data: { toggle: 'pill' }, role: 'tab'} node.js
    %li{role: 'presentation'}
      %a{href: '#ruby', data: { toggle: 'pill' }, role: 'tab'} ruby
    %li{role: 'presentation'}
      %a{href: '#go', data: { toggle: 'pill' }, role: 'tab'} go
    %li{role: 'presentation'}
      %a{href: '#https', data: { toggle: 'pill' }, role: 'tab'} https
  .tab-content.track-code-samples
    .tab-pane.active#nodejs{role: 'tabpanel'}
      %pre
        %code.hljs.javascript
          :preserve
            // Remember to run `npm install --save botmetrics` in your app.
            //
            // If you are using an Express-based app, parse the request body
            // and pass along req.body as an argument to Botmetrics
            // for example:
            var express = require('express');
            var app = express();
            var bodyParser = require('body-parser');
            var Botmetrics = require('botmetrics');

            app.use(bodyParser.json()); // for parsing application/json

            app.post('/webhooks', function(req, res) {
              Botmetrics.track(req.body, {
                apiKey: "#{current_user.api_key}",
                botId: "#{@bot.uid}"
              });
              res.status(200).send("");
            });

            app.listen(5000, function () {
              console.log('facebook bot listening on port 5000!');
            });

    .tab-pane#ruby{role: 'tabpanel'}
      %pre
        %code.hljs.ruby
          :preserve
            # Remember to run `gem install botmetrics-rb`
            # or add the following line to your Gemfile:
            # gem 'botmetrics-rb', require: 'botmetrics'
            #
            # Send the params to Botmetrics using the 'track' API:
            # for e.g. in Rails/Sinatra:

            BotMetrics::Client.new(
              api_key: "#{current_user.api_key}",
              bot_id: "#{@bot.uid}"
            ).track(params)
    .tab-pane#go{role: 'tabpanel'}
      %pre#go
        %code.hljs.go
          :preserve
            // In your Go Request handler, make a call to client.Track
            // with the request body
            import "github.com/botmetrics/go-botmetrics"

            http.HandleFunc("/webhooks", func(w http.ResponseWriter, r *http.Request) {
              postBody, err := ioutil.ReadAll(r.Body)

              if err != nil {
                panic(err)
              }

              client, err := botmetrics.NewBotMetricsClient(
                "#{current_user.api_key}",
                "#{@bot.uid}"
              )
              if err == nil {
                client.Track(postBody)
              }
            })
    .tab-pane#https{role: 'tabpanel'}
      %pre#https
        %code.hljs.bash
          :preserve
            # Botmetrics can also accept events over a HTTPS API.
            # You can POST to this endpoint using the API_KEY and BOT_ID
            # Be sure to escape the quotes in your JSON Payload
            # ie. (\"object\" instead of "object")

            curl -X POST \
            -H "Authorization: #{current_user.api_key}" \
            #{Settings.rails_host || Setting.hostname}/bots/#{@bot.uid}/events \
            -d "format=json&event=json-message-payload"

app/views/bots/_api_slack.html.haml
.api
  %ul.nav.nav-pills.nav-code{role: 'tablist'}
    %li.active{role: 'presentation'}
      %a{href: '#nodejs', data: { toggle: 'pill' }, role: 'tab'} node.js
    %li{role: 'presentation'}
      %a{href: '#ruby', data: { toggle: 'pill' }, role: 'tab'} ruby
    %li{role: 'presentation'}
      %a{href: '#go', data: { toggle: 'pill' }, role: 'tab'} go
    %li{role: 'presentation'}
      %a{href: '#https', data: { toggle: 'pill' }, role: 'tab'} https
  .tab-content.track-code-samples
    .tab-pane.active#nodejs{role: 'tabpanel'}
      %p.api
        You can use the Botmetrics NPM module
        %code botmetrics.js
        available at
        = link_to 'botmetrics/botmetrics.js', 'https://github.com/botmetrics/botmetrics.js#usage-slack'
        to add more instances to your bot.
      %p.api
        Set the following environment variables in your app and follow the
        = link_to 'README', 'https://github.com/botmetrics/botmetrics.js#usage-slack'

      %pre
        %code.hljs.bash
          :preserve
            BOTMETRICS_BOT_ID=#{@bot.uid}
            BOTMETRICS_API_KEY=#{current_user.api_key}

    .tab-pane#ruby{role: 'tabpanel'}
      %p.api
        You can use the Botmetrics Rubygem
        %code botmetrics-rb
        available at
        = link_to 'botmetrics/botmetrics-rb', 'https://github.com/botmetrics/botmetrics-rb#usage-slack'
        to add more instances to your bot.
      %p.api
        Set the following environment variables in your app and follow the
        = link_to 'README', 'https://github.com/botmetrics/botmetrics-rb#usage-slack'

      %pre
        %code.hljs.bash
          :preserve
            BOTMETRICS_BOT_ID=#{@bot.uid}
            BOTMETRICS_API_KEY=#{current_user.api_key}

    .tab-pane#go{role: 'tabpanel'}
      %p.api
        You can use the Botmetrics library
        %code go-botmetrics
        available at
        = link_to 'botmetrics/go-botmetrics', 'https://github.com/botmetrics/go-botmetrics#usage-slack'
        to add more instances to your bot.
      %p.api
        Set the following environment variables in your app and follow the
        = link_to 'README', 'https://github.com/botmetrics/go-botmetrics#usage-slack'

      %pre
        %code.hljs.bash
          :preserve
            BOTMETRICS_BOT_ID=#{@bot.uid}
            BOTMETRICS_API_KEY=#{current_user.api_key}

    .tab-pane#https{role: 'tabpanel'}
      %p.api
        You can easily add more instances to your bot via a HTTP API.
      %pre
        %code.hljs.bash
          :preserve
            curl -X POST \
            -H "Authorization: #{current_user.api_key}" \
            #{Settings.rails_host || Setting.hostname}/bots/#{@bot.uid}/instances \
            -d "format=json&instance[token]=my-bot-token"

app/views/bots/edit.html.haml
.secondary-menu.row
  .col-md-4.col-sm-4.col-xs-4
    %h2 Settings

.row
  .col-md-6
    = simple_form_for [@bot], url: bot_path(@bot), method: :patch do |f|
      = f.input :name, label: "Your Bot's Name", required: true
      - if @bot.webhooks_enabled?
        = f.input :webhook_url, label: webhook_label(@bot)
        %span.small.help-block
          - if @bot.webhook_events.count > 0
            = link_to "View Events", webhook_events_bot_path(@bot)

      = f.submit 'Save'

    - if @bot.provider != 'slack' && (instance = @bot.instances.first).present?
      %h2.teams
        - if @bot.provider == 'facebook'
          Update Page Access token
        - elsif @bot.provider == 'kik'
          Update API Key &amp; Username
      %hr
      = simple_form_for [@bot, instance], url: bot_instance_path(@bot, instance), as: :instance, method: :patch do |f|
        - if @bot.provider == 'kik'
          = f.input :uid, label: "Your Bot's Username", required: true
        = f.input :token, label: new_instance_token_label(@bot), required: true
        = f.submit 'Update Bot'

    %h2.teams Team
    %hr
      %ul
        - @bot.bot_collaborators.joins(:user).each do |bc|
          - user = bc.user
          %li
            = mail_to user.email, user.full_name
            - if current_user == user
              %span (That's you!)
            - if bc.confirmed_at.nil?
              %span (not accepted yet)

      = link_to 'Invite Team Member', new_user_invitation_path, class: 'btn btn-success invite-teammember'
      .add-teammember
        = simple_form_for User.new, as: :invite, url: user_invitation_path, method: :post do |f|
          = f.input :full_name, label: "Your New Team Member's Full Name", required: true
          = f.input :email, label: "Your New Team Member's Email", required: true
          = f.input :timezone, required: true, label: "Your New Team Member's Timezone", as: :time_zone, default: current_user.timezone
          = f.input :bot_id, required: true, input_html: { value: @bot.uid }, as: :hidden
          = f.submit 'Invite Team Member'

    %h2.api Disable Metrics Collection
    %hr
    %p.disable-metrics-collection
      Disable metrics collection for this bot and remove from dashboard view
      = button_to 'Delete Bot', bot_path(@bot), method: :delete, form_class: 'delete-bot', data: { confirm: "Are you sure you want to disable metrics collection for this bot?" }

    %h2.api How To Integrate
    %hr
    - if @bot.provider == 'slack'
      = render partial: 'api_slack'
    - else
      %p.status
        Set up tracking in your bot application by adding this snippet of code:
      = render partial: 'api_others'

- content_for :page_scripts do
  :javascript
    App.page = new App.BotsEdit();
    App.page.run();

app/views/bots/messages_to_bot.html.haml
.secondary-menu.row
  .col-md-3.col-sm-3.col-xs-6
    %h2 Messages To Bot
  .col-md-9.col-sm-9.col-xs-6.text-right
    #report-range.pull-right
      %i.fa.fa-calendar
      %span
      %b.caret
    .btn-group.time-segmented-controls.pull-right
      = link_to 'Day', messages_to_bot_bot_path(@bot), class: (@group_by == 'day' ? 'btn active' : 'btn'), data: { group: 'day' }
      = link_to 'Week', messages_to_bot_bot_path(@bot, group_by: 'week'), class: (@group_by == 'week' ? 'btn active' : 'btn'), data: { group: 'week' }
      = link_to 'Month', messages_to_bot_bot_path(@bot, group_by: 'month'), class: (@group_by == 'month' ? 'btn active' : 'btn'), data: { group: 'month' }

.container-fluid.graph-container
  .graph.row
    .col-md-12.col-sm-12.col-xs-12.graph-container
      = line_chart @messages, solo_chartjs_opts

- content_for :page_scripts do
  :javascript
    App.page = new App.BotsDetail(#{@start.to_json}, #{@end.to_json});
    App.page.run();

app/views/bots/new.html.haml
.row
  .col-md-6.col-md-offset-3
    %h3.text-center
      = "#{current_user.bots.count == 0 ? "Let's create your first bot. " : ""}What platform is it on?"
    = render partial: 'new_bot_form'

app/views/bots/new_bots.html.haml
.secondary-menu.row
  .col-md-3.col-sm-3.col-xs-6
    %h2 New Bots
  .col-md-9.col-sm-9.col-xs-6.text-right
    #report-range.pull-right
      %i.fa.fa-calendar
      %span
      %b.caret
    .btn-group.time-segmented-controls.pull-right
      = link_to 'Day', new_bots_bot_path(@bot), class: (@group_by == 'day' ? 'btn active' : 'btn'), data: { group: 'day' }
      = link_to 'Week', new_bots_bot_path(@bot, group_by: 'week'), class: (@group_by == 'week' ? 'btn active' : 'btn'), data: { group: 'week' }
      = link_to 'Month', new_bots_bot_path(@bot, group_by: 'month'), class: (@group_by == 'month' ? 'btn active' : 'btn'), data: { group: 'month' }

.container-fluid.graph-container
  .graph.row
    .col-md-12.col-sm-12.col-xs-12.graph-container
      = line_chart @new_bots, solo_chartjs_opts

      %table.table.table-striped.tableized
        %thead
          %tr
            %th Team
            %th URL
            %th Members
            %th Created
            %th Bot Interactions
            %th Last Interacted with Bot
        %tbody
          - @tableized.each do |b|
            - _url = b.instance_attributes['team_url']
            - _name = b.instance_attributes['team_name']
            %tr{class: b.id}
              %td= _name
              %td= _url.present? ? link_to(_url, _url) : ''
              %td= b.users_count
              %td= "#{time_ago_in_words(b.created_at)} ago"
              %td= b.events_count
              %td= b.last_event_at.present? ? "#{time_ago_in_words(b.last_event_at)} ago" : 'no messages yet'
      = will_paginate @tableized, renderer: BootstrapPagination::Rails

- content_for :page_scripts do
  :javascript
    App.page = new App.BotsDetail(#{@start.to_json}, #{@end.to_json});
    App.page.run();

app/views/bots/show.html.haml
.secondary-menu.row
  .col-md-4.col-sm-4.col-xs-4
    %h2 All Metrics
  .col-md-8.col-sm-8.col-xs-8.text-right
    .btn-group.time-segmented-controls
      = link_to 'Today', bot_path(@bot), class: (@group_by == 'today' ? 'btn active' : 'btn')
      = link_to 'This Week', bot_path(@bot, group_by: 'this-week'), class: (@group_by == 'this-week' ? 'btn active' : 'btn')
      = link_to 'This Month', bot_path(@bot, group_by: 'this-month'), class: (@group_by == 'this-month' ? 'btn active' : 'btn')
      = link_to 'All Time', bot_path(@bot, group_by: 'all-time'), class: (@group_by == 'all-time' ? 'btn active' : 'btn')

- if @bot.events.count == 0
  .row.integrate-cta.alert-danger
    %p
      We haven't received any events from your bot yet.
      Add the
      = link_to 'Botmetrics SDK', edit_bot_path(@bot), target: '_blank'
      to your codebase in less than 5 minutes!

.stats.row
  - if @bot.provider == 'slack'
    = link_to new_bots_bot_dashboards_path(@bot) do
      .stat.col-sm-6.col-md-3
        %h3 Bots Installed
        = formatted_growth(@dashboarder.new_bots_growth)
        %p.number= number_with_delimiter(@dashboarder.new_bots_count)
        - if @show_trends
          = line_chart @dashboarder.new_bots, dashboard_chartjs_opts
    = link_to disabled_bots_bot_dashboards_path(@bot) do
      .stat.col-sm-6.col-md-3
        %h3 Bots Uninstalled
        = formatted_growth(@dashboarder.disabled_bots_growth)
        %p.number= number_with_delimiter(@dashboarder.disabled_bots_count)
        - if @show_trends
          = line_chart @dashboarder.disabled_bots, dashboard_chartjs_opts
  = link_to users_bot_dashboards_path(@bot) do
    .stat.col-sm-6.col-md-3
      %h3 New Users
      = formatted_growth(@dashboarder.new_users_growth)
      %p.number= number_with_delimiter(@dashboarder.new_users_count)
      - if @show_trends
        = line_chart @dashboarder.new_users, dashboard_chartjs_opts
  - if @bot.provider == 'slack'
    = link_to all_messages_bot_dashboards_path(@bot) do
      .stat.col-sm-6.col-md-3
        %h3 Messages
        = formatted_growth(@dashboarder.messages_growth)
        %p.number= number_with_delimiter(@dashboarder.messages_count)
        - if @show_trends
          = line_chart @dashboarder.messages, dashboard_chartjs_opts
  = link_to messages_to_bot_bot_dashboards_path(@bot) do
    .stat.col-sm-6.col-md-3
      %h3 Messages To Bot
      = formatted_growth(@dashboarder.messages_for_bot_growth)
      %p.number= number_with_delimiter(@dashboarder.messages_for_bot_count)
      - if @show_trends
        = line_chart @dashboarder.messages_for_bot, dashboard_chartjs_opts
  = link_to messages_from_bot_bot_dashboards_path(@bot) do
    .stat.col-sm-6.col-md-3
      %h3 Messages From Bot
      = formatted_growth(@dashboarder.messages_from_bot_growth)
      %p.number= number_with_delimiter(@dashboarder.messages_from_bot_count)
      - if @show_trends
        = line_chart @dashboarder.messages_from_bot, dashboard_chartjs_opts

app/views/bots/users.html.haml
.secondary-menu.row
  .col-md-3.col-sm-3.col-xs-6
    %h2 New Users
  .col-md-9.col-sm-9.col-xs-6
    #report-range.pull-right
      %i.fa.fa-calendar
      %span
      %b.caret
    .btn-group.time-segmented-controls.pull-right
      = link_to 'Day', users_bot_path(@bot), class: (@group_by == 'day' ? 'btn active' : 'btn'), data: { group: 'day' }
      = link_to 'Week', users_bot_path(@bot, group_by: 'week'), class: (@group_by == 'week' ? 'btn active' : 'btn'), data: { group: 'week' }
      = link_to 'Month', users_bot_path(@bot, group_by: 'month'), class: (@group_by == 'month' ? 'btn active' : 'btn'), data: { group: 'month' }

.container-fluid.graph-container
  .graph.row
    .col-md-12.col-sm-12.col-xs-12.graph-container
      = line_chart @users, solo_chartjs_opts

- content_for :page_scripts do
  :javascript
    App.page = new App.BotsDetail(#{@start.to_json}, #{@end.to_json});
    App.page.run();

app/views/bots/verifying_webhook.html.haml
.row
  .col-md-4.col-md-offset-4
    %h3.text-center
      Verifing webhook of #{@bot.name}
    %p.intro
      We are verifying webhook for your bot:
    .progress.progress-striped.active
      .progress-bar.progress-bar-success{ role:'progressbar', 'aria-valuenow' => '50', 'aria-valuemin' => '0', 'aria-valuemax' => '100', style: "width: 50%" }

    .setup-done
      %p.verified-failed Failed to verify webhook, please retry.

      %p.verified-success
        We've setup webhook for your bot. You can go to your dashboard to start analyzing how your bot is doing.

      .go-to-settings.text-center
        = link_to 'Go Back To Settings', edit_bot_path(@bot), class: 'btn btn-lg btn-success'

- content_for :page_scripts do
  :javascript
    App.page = new App.VerifyingWebhook(#{@bot.id.to_json}, #{Settings.pusher_api_key.to_json});
    App.page.run();

app/views/bots/webhook_events.html.haml
.secondary-menu.row
  .col-md-6.col-sm-3.col-xs-6
    = link_to edit_bot_path(@bot), class: 'breadcrumb' do
      %h2 Settings
    %span.breadcrumb-separator
      \/
    %h2 Webhook Events

.container-fluid
  .row
    %h3 Events for #{@bot.webhook_url}
  .row
    .col-xs-12.graph-container
      %table.table.table-striped.tableized
        %thead
          %tr
            %th Response Code
            %th Completed In
            %th Last Sent
        %tbody
          - @tableized.each do |webhook_event|
            %tr{class: webhook_event.id}
              %td= webhook_event.code
              %td= formatted_elapsed_time(webhook_event.elapsed_time)
              %td= "#{time_ago_in_words(webhook_event.created_at)} ago"
      = will_paginate @tableized, renderer: BootstrapPagination::Rails