config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: :registrations, invitations: :invitations }

  resources :settings, only: [:new, :create]

  resources :bots do
    resources :events, only: [:create]
    resources :dashboards, only: [:index, :show, :new, :create, :destroy] do
      member do
        get :load_async
      end
    end

    resources :short_links, only: [:create]
    resources :paths do
      member do
        get :insights
        get :events
      end
    end

    get :verifying_webhook
    get :webhook_events, on: :member

    resources :instances, only: [:new, :create, :show, :edit, :update], controller: :bot_instances do
      member do
        get :setting_up
      end
    end

    resources :users, controller: "bot_users", only: [:update], as: :users

    resources :retention, only: [:index]

    resources :notifications, except: [:new, :create, :edit, :update]
    resources :new_notification, only: [:create] do
      collection do
        get :step_1
        get :step_2
        get :step_3
      end
    end
    resources :edit_notification, only: [:update] do
      member do
        get :step_1
        get :step_2
        get :step_3
      end
    end

    resources :messages, only: [:create]

    resources :insights, only: [:index]
  end

  resources :users, only: [:show, :update] do
    member do
      patch :regenerate_api_key
    end
  end

  resources :short_links, only: [:show], path: 'to'

  root 'static#index'

  get '/.well-known/acme-challenge/:id' => 'static#letsencrypt', protocol: 'http'
  get '/privacy' => 'static#privacy'

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["SIDEKIQ_USERNAME"] && password == ENV["SIDEKIQ_PASSWORD"]
  end

  mount Sidekiq::Web, at: "/sidekiq"

  unless Rails.env.production?
    mount SlackApiMocks, at: "/slack_api_mocks"
    mount FacebookApiMocks, at: "/facebook_api_mocks"
  end
end

app/models/bot_instance.rb
class BotInstance < ActiveRecord::Base
  belongs_to :bot
  has_many :users, class_name: 'BotUser'
  has_many :events
  has_many :messages
  has_many :short_links

  validates_presence_of :token, :bot_id, :provider
  validates_uniqueness_of :token
  validates_inclusion_of  :provider, in: %w(slack kik facebook telegram)
  validates_inclusion_of  :state, in: %w(pending enabled disabled)

  validates_presence_of :uid, if: Proc.new { |bi| bi.state == 'enabled' }

  validates_with BotInstanceAttributesValidator

  scope :legit,     -> { where("bot_instances.state <> ?", 'pending') }
  scope :enabled,   -> { where("bot_instances.state = ?", 'enabled') }
  scope :disabled,  -> { where("bot_instances.state = ?", 'disabled') }

  delegate :owners, to: :bot
  delegate :collaborators, to: :bot

  store_accessor :instance_attributes, :team_id, :team_name, :team_url, :name

  def self.find_by_bot_and_team!(bot, team_id)
    bot_instance = BotInstance.where(bot_id: bot.id).where("instance_attributes->>'team_id' = ?", team_id).first
    bot_instance.presence || (raise ActiveRecord::RecordNotFound)
  end

  def self.with_events(events_relation)
    select("bot_instances.*, COALESCE(users.cnt, 0) AS users_count, e.c_at AS last_event_at").
    joins("LEFT JOIN (SELECT bot_instance_id, COUNT(*) AS cnt FROM bot_users GROUP BY bot_instance_id) users on users.bot_instance_id = bot_instances.id").
    joins("INNER JOIN (SELECT bot_instance_id, MAX(rolledup_events.created_at) AS c_at FROM rolledup_events WHERE rolledup_events.id IN (#{events_relation.to_sql}) GROUP by bot_instance_id) e ON e.bot_instance_id = bot_instances.id").
    order("last_event_at DESC")
  end

  def self.membership_type_from_hash(user_hash)
    membership_type = nil

    if user_hash['deleted']
      membership_type = 'deleted'
    elsif user_hash['is_owner']
      membership_type = 'owner'
    elsif user_hash['is_admin']
      membership_type = 'admin'
    elsif user_hash['is_restricted']
      membership_type = 'guest'
    else
      membership_type = 'member'
    end

    membership_type
  end

  def import_users!
    slack_client = Slack.new(self.token)

    BotInstance.with_advisory_lock("team-import-#{self.uid}") do
      object_nesting_level = 0
      current_user = {}
      current_profile = {}

      current_user_key = nil
      current_profile_key = nil
      _bi = self

      parser = JSON::Stream::Parser.new do
        start_object { object_nesting_level += 1 }
        end_object do
          if object_nesting_level.eql? 2
            _bi.import_user_from_hash!(current_user)
            current_user = {}
          elsif object_nesting_level.eql? 3
            current_user[current_user_key] = current_profile
            current_profile = {}
          end

          object_nesting_level -= 1
        end

        key do |k|
          if object_nesting_level.eql? 2
            current_user_key = k
          elsif object_nesting_level.eql? 3
            current_profile_key = k
          end
        end

        value do |v|
          if object_nesting_level.eql? 2
            current_user[current_user_key] = v
          elsif object_nesting_level.eql? 3
            current_profile[current_profile_key] = v
          end
        end
      end

      slack_client.call('users.list', :get) do |chunk, remaining_bytes, total_bytes|
        parser << chunk
      end
    end

    Rails.logger.warn "[ImportUsersForBotInstanceJob] importing members: #{self.users.count} ID: #{self.id}"
  end

  def import_user_from_hash!(user)
    u = self.users.find_by(uid: user['id']) || self.users.new(uid: user['id'], provider: 'slack')

    u.user_attributes['nickname'] = user['name']
    u.user_attributes['email'] = user['profile']['email']

    u.user_attributes['first_name'] = user['profile']['first_name']
    u.user_attributes['last_name'] = user['profile']['last_name']
    u.user_attributes['full_name'] = user['profile']['real_name']

    u.user_attributes['timezone'] = user['tz']
    u.user_attributes['timezone_description'] = user['tz_label']
    u.user_attributes['timezone_offset'] = user['tz_offset'].to_i
    u.membership_type = BotInstance.membership_type_from_hash(user)
    u.save!
  end

  def bot_team_name
    case provider
    when 'facebook'
      name
    when 'slack'
      team_name
    end
  end
end

app/controllers/bot_instances_controller.rb
class BotInstancesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_bot

  layout 'app'

  def new
    @instance = @bot.instances.build
  end

  def create
    @instance = @bot.build_instance(instance_params)
    @instance.provider = @bot.provider
    if (created_at = params[:instance][:created_at])
      @instance.created_at = Time.at(created_at.to_i)
    end

    if @instance.save
      SetupBotJob.perform_async(@instance.id, current_user.id)

      respond_to do |format|
        format.html { redirect_to setting_up_bot_instance_path(@bot, @instance) }
        format.json { render json: { id: @instance.id }, status: :created }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: { errors: @instance.errors.full_messages }, status: :bad_request }
      end
    end
  end

  def edit
    if @bot.provider == 'slack'
      redirect_to(bot_path(@bot)) && return
    end

    @instance = @bot.instances.first
  end

  def update
    if @bot.provider == 'slack'
      redirect_to(bot_path(@bot)) && return
    end

    @instance = @bot.instances.first

    if @instance.present? && @instance.update_attributes(update_instance_params)
      SetupBotJob.perform_async(@instance.id, current_user.id)

      respond_to do |format|
        format.html { redirect_to setting_up_bot_instance_path(@bot, @instance) }
      end
    else
      respond_to do |format|
        format.html { render :edit }
      end
    end
  end

  def show
    @instance = @bot.instances.find(params[:id])
    render json: { state: @instance.state }
  end

  def setting_up
    @instance = @bot.instances.find(params[:id])
  end

  protected
  def instance_params
    params.require(:instance).permit(:token, :uid, :created_at)
  end

  def update_instance_params
    params.require(:instance).permit(:token)
  end
end

app/helpers/bot_instances_helper.rb
module BotInstancesHelper
  def new_instance_header(bot)
    case bot.provider
    when 'slack'
      bot.instances.legit.count == 0 ? "Let's setup the first instance of your Slack Bot" : "Setup Another Instance of your Slack Bot"
    when 'facebook'
      "Let's Setup Your Facebook Bot"
    when 'kik'
      "Let's Setup Your Kik Bot"
    end
  end

  def new_instance_token_label(bot)
    case bot.provider
    when 'slack'
      "Your Slack Bot's Token"
    when 'facebook'
      "Your Bot's Page Access Token"
    when 'kik'
      "Your Bot's API Key"
    end
  end

  def new_instance_submit_text(bot)
    case bot.provider
    when 'slack'
      "Start Collecting Metrics"
    when 'facebook'
      "Setup Bot"
    when 'kik'
      "Setup Bot"
    end
  end

  def new_instance_disclaimer(bot)
    case bot.provider
    when 'facebook'
      "The page access token is available in 'Products' > 'Messenger' in your <a href='https://developers.facebook.com/' target='_blank'>app's dashboard</a>.".html_safe
    when 'kik'
      "The API Key and Username are available in the 'Configuration' tab of your <a href='https://dev.kik.com/' target='_blank'>Bot Dashboard</a>.".html_safe
    end
  end

  def new_instance_onboarding_image(bot)
    case bot.provider
    when 'facebook'
      image_tag('onboarding/facebook.png', class: 'img img-responsive img-onboarding img-thumbnail')
    end
  end

  def new_instance_tips(bot)
    case bot.provider
    when 'facebook'
      "<div class='onboarding-tips'>" +
        "<h4>Make sure you have the following options selected when setting up your webhook</h4>" +
        "<ul>" +
          "<li>message_deliveries</li>" +
          "<li>message_echoes</li>" +
          "<li>message_reads</li>" +
          "<li>messages</li>" +
          "<li>messaging_account_linking</li>" +
          "<li>messaging_optins</li>" +
          "<li>messaging_postbacks</li>" +
        "</ul>" +
      "</div>"
    end
  end

  def setting_up_header(bot)
    case bot.provider
    when 'slack'
      "Setting Up an Instance of '#{bot.name}'"
    when 'facebook'
      "Setting Up '#{bot.name}'"
    when 'kik'
      "Setting Up '#{bot.name}'"
    end
  end

  def setting_up_intro(bot)
    case bot.provider
    when 'slack'
      "We are setting up metrics collection for your bot..."
    when 'facebook'
      "We are setting up your bot..."
    when 'kik'
      "We are setting up your bot..."
    end
  end
end

app/views/bot_instances/_form.html.haml
.row
  .col-md-5
    - if @bot.provider == 'slack'
      %br
      .api-instructions
        Use the Botmetrics API with Node.JS, Ruby, Go or https to start tracking your Slack Bots:
        = render partial: 'bots/api_slack'
      %hr
      You can also track a Single Bot by entering the Bot Token below:

    = simple_form_for [@bot, @instance], url: bot_instances_path, as: :instance, method: :post do |f|
      - if @bot.provider == 'kik'
        = f.input :uid, label: "Your Bot's Username", required: true
      = f.input :token, label: new_instance_token_label(@bot), required: true
      %p.disclaimer= new_instance_disclaimer(@bot)
      = f.submit new_instance_submit_text(@bot)

  .col-md-7.onboarding-help
    = new_instance_onboarding_image(@bot)
    = raw(new_instance_tips(@bot))

app/views/bot_instances/edit.html.haml
.secondary-menu.row
  .col-md-12
    %h2 Update Your Bot's Page Access Token

= render 'form'

app/views/bot_instances/new.html.haml
.secondary-menu.row
  .col-md-12
    %h2= new_instance_header(@bot)

.row
  .col-md-5
    = simple_form_for [@bot, @instance], url: bot_instances_path, as: :instance, method: :post do |f|
      = f.input :token, label: new_instance_token_label(@bot), required: true
      %p.disclaimer= new_instance_disclaimer(@bot)
      = f.submit new_instance_submit_text(@bot)

    - if @bot.provider == 'slack'
      %hr
      .api-instructions
        Or you can use the API with curl, Ruby or Node.JS:
        = render partial: 'bots/api'
  .col-md-7.onboarding-help
    = new_instance_onboarding_image(@bot)

app/views/bot_instances/setting_up.html.haml
.row
  .col-md-6.col-md-offset-3
    %h3.text-center= setting_up_header(@bot)
    %p.intro= setting_up_intro(@bot)
    .progress.progress-striped.active
      .progress-bar.progress-bar-success{role:"progressbar", 'aria-valuenow' => "50", 'aria-valuemin' => "0", 'aria-valuemax' => "100", style: "width: 50%"}

    .setup-done
      - if @bot.provider == 'slack'
        %p.status
          We've setup metrics collection for your bot. You can go to your dashboard to start analyzing how your bot is doing.
        %p.api
          You can use the API with curl, Ruby or Node.JS:
        = render partial: 'bots/api_slack'
      - else
        %p.status
          %strong Next:
          Set up tracking in your bot application by adding this snippet of code:

        = render partial: 'bots/api_others'

      .go-to-dashboard.text-center
        = link_to bot_path(@bot), class: 'btn btn-lg btn-success' do
          Go To your Bot Dashboard
          %i.fa.fa-arrow-right

      - if @bot.provider == 'slack'
        .create-new-instance.text-center
          = link_to 'Create another instance', new_bot_instance_path(@bot), class: 'btn btn-lg btn-success'
      - elsif @bot.provider == 'facebook'
        .update-instance.text-center
          = link_to 'Update Page Access Token', edit_bot_instance_path(@bot, @instance), class: 'btn btn-lg btn-success'

- content_for :page_scripts do
  :javascript
    App.page = new App.BotInstancesSetup(#{@bot.uid.to_json}, #{@instance.id.to_json}, #{@bot.provider.to_json}, #{Pusher.key.to_json});
    App.page.run();